
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odgteaatruydxlogpbda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZ3RlYWF0cnV5ZHhsb2dwYmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNDI0OTcsImV4cCI6MjA1MzcxODQ5N30.Hc8CzqsWJfxopNaKkIi5EsYJv4tibUZY0phC8_7uL3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
